### ISSUE TITLE
Show element name without corresponding value

### ISSUE THREAD

**Issue by K0nny** [adbuerger/tsysblend#5]
One should be able to show the column name without the current value in each CubeState. 
name = TRUE/FALSE

**Comment by adbuerger** [comment]
I would suggest an option `showValue = True/False` for all States classes

**Comment by adbuerger** [comment]
Please always refer to the commit you closed the issue with, so people know whether and how an issue  was resolved. Int his case, it was 43f818cee8d394ef7b1432127fefda121bd18c3d
