### ISSUE TITLE
Select index as input

### ISSUE THREAD

**Issue by K0nny** [adbuerger/tsysblend#6]
One should be able to select the index of a DataFrame (not only the columns) for a animateSingleElement. This can help you specially if "Time" is set as index.

**Comment by adbuerger** [comment]
Applied to the example

    tc.animateSingleElement((0,-5,12),datafr,"Time")

one could think of a option like

    tc.animateSingleElement((0,-5,12),datafr,"Time", isIndex=True)

so the index of the DataFrame is picked as values, but labeled "time". The default of `ìsIndex` should of course be `False`.
